config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: "posts#index"

  resources :posts do
    resources :messages
    collection do
      get 'search'
    end
  end

  resources :users
end

app/models/post.rb
class Post < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  validates :title,         presence: true
  validates :detail,        presence: true
  validates :image,         presence: true

  has_many :user_posts
  belongs_to :user
  has_many :users, through: :user_posts
  has_one_attached :image
  has_many :messages, dependent: :destroy

  def self.search(search)
    if search != ""
      Post.where('title LIKE(?)', "%#{search}%")
      Post.where('detail LIKE(?)', "%#{search}%")
    else
      Post.all
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, except: [:index, :new, :create, :search]
  before_action :contributor_confirmation, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  

  
  def index
    @posts = Post.includes(:user)
  end
  
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @message = Message.new
    @messages = @post.messages
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    render :show if current_user != @post.user
    redirect_to root_path if @post.destroy
  end

  def search
    @posts = Post.search(params[:keyword])
  end





  private

  def post_params
    params.require(:post).permit(:title, :detail, :image).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def contributor_confirmation
    redirect_to root_path unless current_user == @post.user
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |f|%>
<%= render 'posts/error_messages', model: f.object %>
  <div class="field">
    <%= f.label :title, "タイトル" %><br />
    <%= f.text_field :title, class:"ip-box" %>
  </div>

  <div class="field">
    <%= f.label :detail, "詳細" %><br />
    <%= f.text_area :detail, class:"ar-box" %>
  </div>

  <div class="field">
    <%= f.label :image, "画像" %><br />
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit "投稿する", class: :form__btn %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="card">
  <%= link_to image_tag(post.image, class: :card__img ), post_path(post), method: :get %>
  <div class="card__body">
    <%= link_to post.title, post_path(post), method: :get, class: :card__title%>
    <p class="card__summary">
      <%= post.detail %>
    </p>
    <%= link_to "by #{post.user.nickname}", user_path(post.user), class: :card__user %>
  </div>
</div>

app/views/posts/edit.html.erb
    <div class="form__wrapper">
      <h2 class="page-heading">投稿記事の編集</h2>
      <%= render partial: "form", locals: { post: @post } %>
    </div>

app/views/posts/index.html.erb
<div class="wrapper">
  <div class="chat">
    <% if user_signed_in? %>
      <div class="greeting"> 
        ようこそ！<%= link_to "#{current_user.nickname}", user_path(current_user), class: :greeting__link%> さん
      </div> 
      <% else %>
      <div class="greeting"> 
        ようこそ！ Come Together へ！！
      </div> 
    <% end %>
    <div class="card__wrapper">
      <%= render partial: 'post', collection: @posts %>
    </div>
    <%= link_to( new_post_path, class: 'post-btn') do %>
        <span class='post-btn-text'>♪投稿する♪</span>
    <% end %>
  </div>
  <div class="side-bar">
   <%= form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |f| %>
          <%= f.text_field :keyword, placeholder: "投稿を探す!", class: "input-box" %>
            <button class="search-button">
              <%= image_tag "search.jpg", class:"search-icon" %>
            </button>
          <% end %>

       </div>
  </div>
</div>

app/views/posts/new.html.erb
    <div class="new__wrapper">
      <h2 class="page-heading">新規投稿</h2>
        <%= render partial: "form", locals: { post: @post } %>
    </div>

app/views/posts/search.html.erb
<div class="wrapper">
  <div class="chat">
   <%= form_with(url: search_posts_path, local: true, method: :get) do |form| %><% end %>
  <div class="greeting"> 
        検索結果
      </div> 
        <div class="card__wrapper">
          <% @posts.each do |post| %>
            <%= render partial: "post", locals: { post: post } %>
          <% end %>
        </div>
        <%= link_to( new_post_path, class: 'post-btn') do %>
        <span class='post-btn-text'>♪投稿する♪</span>
        <% end %>
  </div>
      <div class="side-bar">
      <%= form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |f| %>
          <%= f.text_field :keyword, placeholder: "投稿を探す!", class: "input-box" %>
            <button class="search-button">
              <%= image_tag "search.jpg", class:"search-icon" %>
            </button>
          <% end %>
      </div>
</div>

app/views/posts/show.html.erb
    <div class="post__wrapper">
      <p class="post__hedding">
        <%= @post.title %>
      </p>
      <%= link_to "by #{@post.user.nickname}", user_path(@post.user), class: :post__user %>
      <% if current_user == @post.user%>
        <div class="post__manage">
          <%= link_to "編集する", edit_post_path(@post), class: :post__btn %>
           <p class='or-text'> or </p>
          <%= link_to "削除する", post_path(@post), method: :delete, class: :post_d_btn %>
        </div>
      <% end %>
      <div class="post__body">
        <div class="post__detail">
            <%= image_tag @post.image, class: :post__img %>
        </div>
        <div class="post__detail">
          <p class="detail__title">タイトル</p>
          <p class="detail__message">
            <%= @post.title %>
          </p>
        </div>
        <div class="post__detail">
          <p class="detail__title">詳細</p>
          <p class="detail__message">
            <%= @post.detail %>
          </p>
        </div>
      </div>

      <div class="post__messages">
         <% if user_signed_in?%>
          <%= form_with model: [@post, @message], local: true do |f|%>
            <div class="field">
                <div class="massage_p"><%= f.label :content, "メッセージ", class: :m_field %></div>
                 <%= render 'posts/error_messages', model: f.object %><br>
                <%= f.text_area :content, class:"ar-box" %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn %>
            </div>
          <% end %>
        <% end %>
         <div class="messages_lists">
            <% @messages.each do |message| %>
              <li class="messages_list">
                <%= message.content %> 
                <%= link_to "by : [ #{message.user.nickname} ]", user_path(message.user), class: :message_user %>
              </li>
           <% end %>
          </div> 
      </div>
    </div>


 